strategy: latest-minor

repositories:
  - id: google
    url: https://dl.google.com/dl/android/maven2
    includeGroups:
      - androidx.
      - com.google.android.
  - id: central
    url: https://repo1.maven.org/maven2

output:
  targets:
    - format: table
    - format: json
      file: reports/updates.json
